// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgi2uCWxL-QLW91iorDMakgWFE2GlGoNI',
    appId: '1:660724537236:web:90ea2aaa8d8057a9be2181',
    messagingSenderId: '660724537236',
    projectId: 'budgetbuddy-34e4e',
    authDomain: 'budgetbuddy-34e4e.firebaseapp.com',
    storageBucket: 'budgetbuddy-34e4e.firebasestorage.app',
    measurementId: 'G-NRCW38EV03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw0kk3SPT9g8GnY2cTi6yDbiD5IF68LRI',
    appId: '1:660724537236:android:30e608f3fac3e9d3be2181',
    messagingSenderId: '660724537236',
    projectId: 'budgetbuddy-34e4e',
    storageBucket: 'budgetbuddy-34e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdlpfNNqHed8K6W6YSRQgSTYYxus1nx_Q',
    appId: '1:660724537236:ios:e1712f022ee5e5cfbe2181',
    messagingSenderId: '660724537236',
    projectId: 'budgetbuddy-34e4e',
    storageBucket: 'budgetbuddy-34e4e.firebasestorage.app',
    androidClientId: '660724537236-lgm3v5ro1hgp2caf30r26ut474qijpku.apps.googleusercontent.com',
    iosClientId: '660724537236-lr1eof8dcdbb8qujicetu80cpr2ahthm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdlpfNNqHed8K6W6YSRQgSTYYxus1nx_Q',
    appId: '1:660724537236:ios:e1712f022ee5e5cfbe2181',
    messagingSenderId: '660724537236',
    projectId: 'budgetbuddy-34e4e',
    storageBucket: 'budgetbuddy-34e4e.firebasestorage.app',
    androidClientId: '660724537236-lgm3v5ro1hgp2caf30r26ut474qijpku.apps.googleusercontent.com',
    iosClientId: '660724537236-lr1eof8dcdbb8qujicetu80cpr2ahthm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackit',
  );
}
